### PR TITLE
Small misc improvements

### PR DESCRIPTION
**Pull request by zihadmahiuddin**

### CODE REVIEW

**Comment by YusufOzmen01** [comment]
god I should get rid of height xD

**Comment by YusufOzmen01** [comment]
yoo with async-channels I don't need Arc<Mutex<>>?

**Comment by YusufOzmen01** [comment]
kinda poggers ngl

**Comment by zihadmahiuddin** [comment]
> yoo with async-channels I don't need Arc<Mutex<>>?

Nope. I wish tokio did it with theirs too, but it is what it is.

**Comment by zihadmahiuddin** [comment]
> kinda poggers ngl

Yea, they still use Arc but under the hood, much better for us

**Comment by YusufOzmen01** [comment]
I mean tokio's mostly just std library but async so they might've thought to keep everything the same

**Comment by YusufOzmen01** [comment]
welp LGTM

**Pull request merged**
